kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
name: regular-cluster-no-kindnet
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  apiServerPort: 6443
  disableDefaultCNI: true
